name: Calculate Coverage Stats
on:
  workflow_dispatch:
  -
jobs:
  hello:
    name: Self test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Run calculation
      uses: ./

